export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_BALANCE = 'SET_BALANCE';
export const SET_CONTRACTS = 'SET_CONTRACTS';

export const SET_INITIAL_LOADING = 'SET_INITIAL_LOADING';
export const SET_PURCHASE_LOADING = 'SET_PURCHASE_LOADING';
